function test_suite = testdeletedb %#ok<STOUT>
initTestSuite;

function tStruct = setup %#ok<DEFNU>
tStruct = struct('name', 'testdb', 'hostname', 'localhost', ...
    'user', 'postgres', 'password', 'admin', 'DB', []);
try
    tStruct.DB = Mobbed(tStruct.name, tStruct.hostname, tStruct.user, ...
        tStruct.password);
catch ME %#ok<NASGU>
    Mobbed.createdb(tStruct.name, tStruct.hostname, tStruct.user, ...
        tStruct.password, 'mobbed.sql', false);
    tStruct.DB = Mobbed(tStruct.name, tStruct.hostname, tStruct.user, ...
        tStruct.password);
end

function testdeletedbExist(tStruct) %#ok<DEFNU>
fprintf('It should delete a database that exists\n');
tStruct.DB.close();
Mobbed.deletedb(tStruct.name, tStruct.hostname, tStruct.user, ...
    tStruct.password);

function testdeleteddbNotExist(tStruct) %#ok<DEFNU>
fprintf(['It should throw an exception when deleting a database that' ...
    ' does not exist']);
tStruct.DB.close();
Mobbed.deletedb(tStruct.name, tStruct.hostname, tStruct.user, ...
    tStruct.password);
assertExceptionThrown(...
    @() error(Mobbed.createdb(tStruct.name, tStruct.hostname, ...
    tStruct.user, tStruct.password, 'mobbed.sql', false)), ...
    'MATLAB:maxlhs');