function configPath = inputdbcreds
f = figure('Toolbar', 'none', 'MenuBar', 'none', ...
    'WindowStyle', 'modal', 'Resize', 'off', 'DockControls', 'on', ...
    'Color', [0.941176 0.941176 0.941176], ...
    'Units', 'normalized', 'Position', [.5, .4, .3, .5], ...
    'NumberTitle','off', 'Name', 'Database Credentials');
dbp = uipanel('Parent', f,'FontSize',12,'Title', 'Database Credentials', ...
    'Position',[.05 .4 .9 .55], 'TitlePosition', 'centertop');
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Database name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .85 .3 .1]);
uicontrol('Parent', dbp, 'Tag', 'dbname',...
    'style','edit', 'BackgroundColor', 'w', ...
    'String', 'mobbed', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .85 .5 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Host name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .65 .3 .1]);
uicontrol('Parent', dbp, 'Tag', 'hostname',...
    'style','edit', 'BackgroundColor', 'w', ...
    'String', 'localhost', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .65 .5 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Port number', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .45 .3 .1]);
uicontrol('Parent', dbp, 'Tag','port', ...
    'style','edit', 'BackgroundColor', 'w', ...
    'String', '5432', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .45 .2 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'User name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .25 .3 .1]);
uicontrol('Parent', dbp, 'Tag', 'username',...
    'style','edit', 'BackgroundColor', 'w', ...
    'String', 'postgres', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .25 .5 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Password', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .05 .3 .1]);
[hComp, hContainer] = javacomponent('javax.swing.JPasswordField', [.35 .1 .5 .1], dbp);
set(hContainer, 'units','norm', 'Position', [.355 .05 .5 .1]);

cfp = uipanel('Parent', f,'FontSize',12,'Title', 'Configuration File', ...
    'Position',[.05 .15 .9 .2], 'TitlePosition', 'centertop');
uicontrol('Parent', cfp, ...
    'style','text', 'string', 'File name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .7 .3 .3]);
uicontrol('Parent', cfp, 'Tag', 'filename', ...
    'style','edit', 'BackgroundColor', 'w', ...
    'String', 'config.properties', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .7 .5 .3]);
fighandles = guihandles(f);
uicontrol('Parent', cfp, ...
    'style','text', 'string', 'Directory', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .1 .3 .3]);
uicontrol('Parent', cfp, ...
    'style', 'pushbutton', ...
    'String', 'Browse', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .1 .3 .3], ...
    'Callback', {@browseButtonCallback, fighandles});
uicontrol('Parent', f, ...
    'style', 'pushbutton', ...
    'String', 'OK', 'HorizontalAlignment', 'Right', ...
    'Units', 'normalized', 'Position', [.5 .05 .2 .05], ...
    'Callback', {@okButtonCallback, fighandles, hComp});
uicontrol('Parent', f, ...
    'style', 'pushbutton', ...
    'String', 'Cancel', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.75 .05 .2 .05], ...
    'Callback', @closeButtonCallback);
configPath = [];
uiwait(f);


    function browseButtonCallback(hObject, ~, handles)
        handles.directory = uigetdir();
        guidata(hObject,handles);
    end % browseButtonCallback

    function closeButtonCallback(src, eventdata) %#ok<INUSD>
        close;
    end % closeButtonCallback

    function okButtonCallback(~, ~, handles, passObj) 
        dbname = get(handles.dbname, 'String');
        hostname = get(handles.hostname, 'String');
        port = get(handles.port, 'String');
        username = get(handles.username, 'String');
        password = char(passObj.getText);
        filename = get(handles.filename, 'String');
        if ~isempty(port)
            hostname = [hostname ':' port];
        end
        if isfield(handles, 'directory') && handles.dirctory ~= 0
            directory = get(handles.directory, 'string');
            configPath = [directory filesep filename];
        else
            configPath = [pwd filesep filename];
        end
        edu.utsa.mobbed.ManageDB.createCredentials(configPath, ...
            dbname, hostname, username, password);
        close;
    end % closeButtonCallback

end % inputdbcreds