function passwordDemo

f = figure('Toolbar', 'none', 'MenuBar', 'none', ...
    'WindowStyle', 'modal', 'Resize', 'off', 'DockControls', 'on', ...
    'Color', [0.941176 0.941176 0.941176], ...
    'Units', 'normalized', 'Position', [.5, .4, .3, .5], ...
    'NumberTitle','off', 'Name', 'Database Credentials');

dbp = uipanel('Parent', f,'FontSize',12,'Title', 'Database Credentials', ...
    'Position',[.05 .4 .9 .55], 'TitlePosition', 'centertop');
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Database name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .85 .3 .1]);
uicontrol('Parent', dbp, ...
    'style','edit', 'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .85 .5 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Host name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .65 .3 .1]);
uicontrol('Parent', dbp, ...
    'style','edit', 'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .65 .5 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Port number', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .45 .3 .1]);
uicontrol('Parent', dbp, ...
    'style','edit', 'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .45 .2 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'User name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .25 .3 .1]);
uicontrol('Parent', dbp, ...
    'style','edit', 'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .25 .5 .1]);
uicontrol('Parent', dbp, ...
    'style','text', 'string', 'Password', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .05 .3 .1]);
[~,hContainer] = javacomponent('javax.swing.JPasswordField', [.35 .1 .5 .1], dbp);
set(hContainer, 'units','norm', 'Position', [.355 .05 .5 .1]);

cfp = uipanel('Parent', f,'FontSize',12,'Title', 'Configuration File', ...
    'Position',[.05 .15 .9 .2], 'TitlePosition', 'centertop');
uicontrol('Parent', cfp, ...
    'style','text', 'string', 'File name', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .66 .3 .3]);
uicontrol('Parent', cfp, ...
    'style','edit', 'BackgroundColor', 'w', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .66 .5 .3]);
uicontrol('Parent', cfp, ...
    'style','text', 'string', 'Directory', ...
    'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.05 .25 .3 .3]);
uicontrol('Parent', cfp, ...
    'style', 'pushbutton', ...
    'String', 'Browse', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.35 .25 .3 .3]);
uicontrol('Parent', f, ...
    'style', 'pushbutton', ...
    'String', 'OK', 'HorizontalAlignment', 'Right', ...
    'Units', 'normalized', 'Position', [.5 .05 .2 .05]);
uicontrol('Parent', f, ...
    'style', 'pushbutton', ...
    'String', 'Cancel', 'HorizontalAlignment', 'Left', ...
    'Units', 'normalized', 'Position', [.75 .05 .2 .05]);